# Generated by Django 5.2.15 on 2026-06-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('categorie', models.CharField(blank=True, choices=[('PAIEMENT_FACTURE', 'Paiement facture'), ('ACOMPTE', 'Acompte'), ('AUTRE_RECETTE', 'Autre recette'), ('ACHAT_MATERIEL', 'Achat matériel'), ('LOYER', 'Loyer'), ('SALAIRE', 'Salaire'), ('TRANSPORT', 'Transport'), ('AUTRE_DEPENSE', 'Autre dépense')], max_length=30, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
