# Generated by Django 5.2.15 on 2026-06-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_facture_statut'),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.facture'),
        ),
    ]
