# Generated by Django 5.2.15 on 2026-06-06 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom_entreprise', models.CharField(blank=True, max_length=150, null=True)),
                ('ice', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Draft'), ('ENVOYE', 'Sent'), ('ACCEPTE', 'Accepted'), ('REFUSE', 'Refused'), ('EXPIRE', 'Expired')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_validite', models.DateField()),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Cash'), ('VIREMENT', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='devis.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
            ],
            options={
                'verbose_name': 'Quote Line',
            },
        ),
    ]
