# Generated by Django 5.2.15 on 2026-06-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
