# Generated by Django 5.2.15 on 2026-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_alter_devis_client_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Draft'), ('ENVOYE', 'Sent'), ('ACCEPTE', 'Accepted'), ('REFUSE', 'Refused'), ('EXPIRE', 'Expired'), ('ARCHIVE', 'Archived')], default='BROUILLON', max_length=20),
        ),
    ]
