# Generated by Django 5.2.15 on 2026-06-22 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_devis_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='devis',
            unique_together={('user', 'numero')},
        ),
    ]
