# Generated by Django 5.2.15 on 2026-06-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_financement', models.CharField(choices=[('FONCTIONNEMENT', 'Crédit de fonctionnement'), ('INVESTISSEMENT', "Crédit d'investissement"), ('AVANCE_FACTURE', 'Avance sur factures')], max_length=20)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.PositiveIntegerField()),
                ('objet_financement', models.TextField()),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', "En cours d'analyse"), ('FAVORABLE', 'Décision favorable'), ('DEFAVORABLE', 'Décision défavorable'), ('DOSSIER_INCOMPLET', 'Dossier incomplet')], default='SOUMISE', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('score_eligibilite', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('niveau_eligibilite', models.CharField(blank=True, max_length=10, null=True)),
                ('consentement_cndp', models.BooleanField(default=False)),
                ('date_consentement', models.DateTimeField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_financement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de financement',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CIN', 'CIN'), ('RC_PATENTE', 'RC / Patente'), ('RELEVE_BANCAIRE', 'Relevé bancaire'), ('AUTRE', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='justificatifs/%Y/%m/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='credit.demandefinancement')),
            ],
            options={
                'verbose_name': 'Justificatif',
            },
        ),
        migrations.CreateModel(
            name='OffreFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenaire_nom', models.CharField(max_length=150)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duree_mois', models.PositiveIntegerField()),
                ('mensualite_estimee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_portail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='credit.demandefinancement')),
            ],
            options={
                'verbose_name': 'Offre de financement',
            },
        ),
    ]
