# Generated by Django 5.2.15 on 2026-06-18 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rappel_facture_impayee', models.BooleanField(default=True)),
                ('rappel_facture_jours', models.PositiveIntegerField(default=3)),
                ('rappel_devis_expirant', models.BooleanField(default=True)),
                ('rappel_devis_jours_avant', models.PositiveIntegerField(default=3)),
                ('rappel_declaration_fiscale', models.BooleanField(default=True)),
                ('rappel_cotisation_cnss', models.BooleanField(default=False)),
                ('notification_demande_credit', models.BooleanField(default=True)),
                ('canal_in_app', models.BooleanField(default=True)),
                ('canal_push', models.BooleanField(default=True)),
                ('canal_sms', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
            },
        ),
    ]
